version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - kdeininger
  ignore:
  - dependency-name: bootstrap
    versions:
    - ">= 4.a, < 5"
  - dependency-name: google-closure-compiler
    versions:
    - "> 20170910.0.0"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - kdeininger
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 5.a, < 6"
  - dependency-name: pytest
    versions:
    - ">= 6.a, < 7"
  - dependency-name: pytest-cov
    versions:
    - "> 2.5.1, < 3"
  - dependency-name: twine
    versions:
    - ">= 2.a, < 3"
  - dependency-name: twine
    versions:
    - ">= 3.a, < 4"
  - dependency-name: pyyaml
    versions:
    - 5.4.1
