image: python:3.6

before_script:
  - mkdir -p "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - node_modules/

test-py:2.7:
  stage: test
  image: python:2.7
  allow_failure: false
  script:
    - pip install -r requirements.txt
    - git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`
    - flake8
    - py.test -vv --cov-config .coveragerc --cov oereb_client test/py

test-py:3.6:
  stage: test
  allow_failure: false
  cache:
    key: "PIP"
    paths:
      - "$CI_PROJECT_DIR/.pip-cache"
  script:
    - pip install -r requirements.txt
    - git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`
    - flake8
    - py.test -vv --cov-config .coveragerc --cov oereb_client test/py


test-js:
  stage: test
  image: node:latest
  script:
    - git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`
    - npm install
    - ./node_modules/.bin/eslint oereb_client/static/js/**/*.js test/js/**/*.spec.js
    - python node_modules/google-closure-library/closure/bin/build/depswriter.py
      --root_with_prefix="./oereb_client/static/js ../../../../oereb_client/static/js"
      --root_with_prefix="./node_modules/google-closure-library/closure/goog ../../../../node_modules/google-closure-library/closure/goog"
      > test/js/deps.js
    - ./node_modules/.bin/karma start karma.conf.js

codeclimate:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]
