name: Run Python tests

on: push

jobs:
  test-py-2.7:
    name: Test Python 2.7
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: Run checks
          run: >-
            make git-attributes
            make lint-py
            make test-py